# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
#xcode_workspace: Example/GlyuckDataGrid.xcworkspace
#xcode_scheme: GlyuckDataGrid-Example
cache: cocoapods
podfile: Example/Podfile
osx_image: xcode7.1
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example
install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
- xctool -workspace Example/GlyuckDataGrid.xcworkspace -scheme GlyuckDataGrid-Example clean
- xctool -workspace Example/GlyuckDataGrid.xcworkspace -scheme GlyuckDataGrid-Example -sdk iphonesimulator build CODE_SIGNING_REQUIRED=NO
- xctool -workspace Example/GlyuckDataGrid.xcworkspace -scheme GlyuckDataGrid-Example -sdk iphonesimulator test CODE_SIGNING_REQUIRED=NO
